### ISSUE TITLE
注释全是乱码！

### ISSUE THREAD

**Issue by luoka** [xutao1988/XutaoDemo#2]

**Comment by xutao1988** [comment]
我这边是正常的，可能需要你设置一下Eclipse的编码格式。

**Comment by henix** [comment]
在网页上看也是乱码 https://github.com/xutao1988/XutaoDemo/blob/master/src/com/xutao/xutaodemo/MainListActivity.java
你文件的编码没用 UTF-8 ，我估计

**Comment by xutao1988** [comment]
果然，已改。
